CREATE ROLE company_user
  LOGIN
  PASSWORD 'com123';

-- Permissões
GRANT CONNECT ON DATABASE company TO company_user;
GRANT USAGE ON SCHEMA public TO company_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO company_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO company_user;

-- Para futuras tabelas:
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO company_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO company_user;